version: "3"

services:
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  varnish:
    image: varnish:latest 
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl 
    depends_on:
      - nginx 
