version: "3"

services:
  web_app_1:
    build:
      context: ./web_app_1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  web_app_2:
    build:
      context: ./web_app_2
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  varnish:
    image: varnish:latest 
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl 
    depends_on:
      - web_app_1
      - web_app_2

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - varnish

