version: "3"

services:
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - redis
      - redis_exporter
      - web_app 

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
