version: "3"

services:
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


