global:
  scrape_interval: 5s
  scrape_timeout: 2s

scrape_configs:
  - job_name: services
    metrics_path: /metrics 
    static_configs:
      - targets: 
        - 'prometheus:9090' ## prometheus
        - 'web_app:5001' ## web_app
        - 'redis_exporter:9121' ## redis

